[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "helloworld"
dynamic = ["version"]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
helloworld = "helloworld.__main__:main"

[tool.setuptools_scm]