[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "helloworld"
dynamic = ["version"]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools_scm]